backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/resources/img"
public_folder: "/resources/img"

collections:
  - label: "Home"
    name: "home"
    folder: "src/index.md"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text", name: "text", widget: "string" }