backend:
  name: git-gateway
  repo: BiigFish/uotawa-mec
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/resources/img"
public_folder: "/resources/img"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/index.md"
        fields:
          - { label: "Donate Button", name: "DonateButton", widget: "string" }
          - label: "Video"
            name: "video"
            widget: "file"
            default: "/resources/img/Spencer-West.mp4"
          - { label: "Video Poster", name: "videoposter", widget: "image" }
      - label: "Donate Page"
        name: "donate"
        file: "src/donate.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Equipment Box", name: "body", widget: "markdown" }
          - { label: "Equipment Button Link", name: "button1link", widget: "string" }
          - { label: "Equipment Button Text", name: "button1text", widget: "string" }
          - { label: "Monetary Title", name: "monetaryTitle", widget: "string" }
          - { label: "Monetary subTitle", name: "monetaryTextTitle", widget: "string" }
          - { label: "Monetary Text", name: "monetaryText", widget: "string" }
          - { label: "Monetary Button Link", name: "button2link", widget: "string" }
          - { label: "Monetary Button Text", name: "button2text", widget: "string" }
      - label: "About Page"
        name: "about"
        file: "src/about.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact Page"
        name: "contact"
        file: "src/contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Alert Page"
        name: "alert"
        file: "src/alert.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    files:
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Website Title", name: "name", widget: "string" }
          - { label: "Website Short Title", name: "name2", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Alert Banner"
            name: "AlertBanner"
            widget: "select"
            options:
              - { label: "Show", value: "block" }
              - { label: "Hide", value: "hidden" }
          - { label: "Alert", name: "AlertText", widget: "string" }
          - label: "Sponsors"
            name: "sponsor"
            widget: "list"
            create: "true"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Message", name: "message", widget: "string" }
